### ISSUE TITLE
2.0 - Failed to download platform sources

### ISSUE THREAD

**Issue by Undin** [JetBrains/intellij-platform-gradle-plugin#1614]
### What happened?

When I try looking at the source code of some platform class (for example, `AnAction`), IDE doesn't show it by default (it seems it's expected). But if I invoke `Download...` from editor notification, it also fails to attach IDE sources

https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/2539310/78a7f328-7e3a-4349-8036-da334d80890a

### Steps to reproduce

- Clone https://github.com/Undin/intellij-platform-gradle-plugins-bugs/tree/master
- Open `AnAction` class and press `Download...` option in editor notification

### Gradle IntelliJ Plugin version

2.0.0-SNAPSHOT

### Gradle version

8.7

### Operating System

macOS

**Comment by jonathanlermitage** [comment]
I have the same issue. Using IJ Ultimate 2024.1.2.

**Comment by jonathanlermitage** [comment]
Same with 2024.1.4.

**Comment by jonathanlermitage** [comment]
Thx https://jetbrains-platform.slack.com/archives/C05C80200LS/p1719407595946569?thread_ts=1719328643.909549&cid=C05C80200LS, with 2024.1.4, after reloading Gradle project, I now see the "Download Platform sources" (something like that) and, this time, it worked.

**Comment by jonathanlermitage** [comment]
BTW, thre is another issue: I have to do this for every project, and it downloads sources again. May be related to https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1639 ?

**Comment by dowenliu-xyz** [comment]
But for bundled community plugin (i.e. java), the source codes are still not attached.

**Comment by hsz** [comment]
To be fixed [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and released in IntelliJ IDEA 2024.1.5 and 2024.2.

**Comment by hsz** [comment]
I tis now fixed with [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and will be released in IntelliJ IDEA 2024.1.5 and 2024.2.

**Comment by JensWinkler91** [comment]
It's still not working for **BundledPlugins** , .e.g. `bundledPlugins("Git4Idea", "JavaScript", "Docker")` .

The **Download Intellij Platform sources** action appears, I still see the decompiled class file after I executed it.
![image](https://github.com/user-attachments/assets/ccacf253-2a7e-41ea-99d4-b1aec484a8f7)

However, downloading the sources for .e.g. **com.intellij.execution.configurations.RunConfiguration** worked fine.

**I tried it with the IntelliJ 2024.2 as you can see:**
![image](https://github.com/user-attachments/assets/51efe7af-a81e-4c2d-aeac-a43be6995fd0)
![image](https://github.com/user-attachments/assets/bf405dcf-6781-4c99-a257-62fd114619ee)


Do I miss something?
