### ISSUE TITLE
Should support runIde with multi-module plugin

### ISSUE THREAD

**Issue by Vanco** [JetBrains/intellij-platform-gradle-plugin#1620]
### Describe the need of your request

Let's make a multi-module plugin project `DemoPlugin`, it contains `DemoPluginBase` and `DemoPluginExt` mudule.  The `DemoPluginBase` is a plugin whitch expose an extention point, and the `DemoPluginExt` is a plugin make use the extention point from `DemoPluginBase`.  During the developing phese, I need to run gradle task `:DemoPluginExt:runIde`,  how to config the plugin dependcency to make  both `DemoPluginBase` and `DemoPluginExt` deploy to the .sandbox and run it?

### First attempt
**DemoPluginExt/build.gradle.kts**
```
dependencies {
    implementation(project(":DemoPluginBase"))
    intellijPlatform {
        bundledPlugins("?")
        plugins("?")
     }
}
```
If I config like this, the `DemoPluginExt` will include all jar from `DemoPluginBase`, whitch is not what I expected. 

### Second attempt
**DemoPluginExt/build.gradle.kts**
```
dependencies {
    intellijPlatform {
        bundledPlugins("?")
        plugins("DemoPluginBase")
     }
}
```
 how do I put the `DemoPluginBase` in the plugin dependency?  because the `DemoPluginBase` is not release yet, it was not in repository, it is not a bundledPlugin too.  where to put local-in-developing plugin in the plugin dependency?

And the sandbox only contain `DemoPluginExt` when I run `:DemoPluginExt:runIde`, should have `DemoPluginBase` also.
**sandbox**
```
.IntelliJIDEAx0/
└── plugins
    └── DemoPluginExt
        └── lib
            │   ...
```

### Proposed solution

**DemoPluginExt/build.gradle.kts**
```
dependencies {
    intellijPlatform {
        bundledPlugins("?")
        plugins(project(":DemoPluginBase"))
     }
}
```

**sandbox**
```
.IntelliJIDEAx0/
└── plugins
    └── DemoPluginBase
        └── lib
             │   ...
    └── DemoPluginExt
        └── lib
            │   ...
```

**Comment by hsz** [comment]
@Vanco Thank you for filing the issue!

In the `2.0.0-SNAPSHOT` release you'll find the latest changes that include `localPlugin` helper, which can be used as follows:

```kotlin
dependencies {
    intellijPlatform {
        // use ProjectDependency
        localPlugin(project(":DemoPluginBase"))

        // use a File/String/Directory to pass a directory with extracted plugin
        localPlugin("/path/to/plugin/")

        // use a File/String to pass a path to the plugin ZIP archive
        localPlugin("/path/to/plugin.zip")
     }
}
```

The same helper is also available for customizable tasks, like:

```kotlin
tasks {
    val runPhpStormWithLocalPlugin by registering(CustomRunIdeTask::class) {
        type = IntelliJPlatformType.PhpStorm

        plugins {
            localPlugin(...)
        }
    }
}
```

Please let me know, if this works for you!

**Comment by Vanco** [comment]
@hsz Thank you for quick respond!

I tried with `localPlugin(project(":DemoPluginBase"))` and it still not work.
the **.sandbox** looks like:
```
.IntelliJIDEAx0/
└── plugins
    └── jarOfBase.jsr // missing plugin directory
    └── DemoPluginExt
        └── lib
            │   jarOfExt.jar
```

expected this structure:
```
.IntelliJIDEAx0/
└── plugins
    └── DemoPluginBase
        └── lib
             │   jarOfBase.jar
    └── DemoPluginExt
        └── lib
            │   jarOfExt.jar
```

That means:  If I run `:DemoPluginExt:runIde`, Both `:DemoPluginBase` and `:DemoPluginExt` directory should prepared in the `.IntelliJIDEAx0/pluigins` directory.

**Comment by hsz** [comment]
Could you provide a minimal reproducible example so I could test it locally?

**Comment by Vanco** [comment]
Sure. please use this democode.
[muti-plugin.zip](https://github.com/JetBrains/intellij-platform-gradle-plugin/files/15396651/muti-plugin.zip)
all the jar should be in `plugin-base/lib` directory
 
![screen](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/11991700/f606e92b-3f40-4fbb-942d-673459167a6e)

**Comment by Vanco** [comment]
![screen](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/11991700/1325081a-6e8c-498e-865b-feaf910a4679)

**Comment by novotnyr** [comment]
@Vanco please try the `beta3`. I tried to use your plugin and looks like it is fixed.

**Comment by Vanco** [comment]
@novotnyr I tried, and the issue still there.   

I think you don't really understand the issue. Let me explain the problem to you in detail.
The `plugin-base` contain four jars in the plugin:
```
plugin-base
        └── lib
             │   batik-all-1.17.jar
             │   plugin-base-1.0-SNAPSHOT-instrumented.jar
             │   xml-apis-ext-1.3.04.jar
             │   xmlgraphics-commons-2.9.jar
```

and the `plugin-ext` contain one jars in the plugin:
```
plugin-ext
        └── lib
            │   plugin-ext-1.0-SNAPSHOT-instrumented.jar
```

When it deployed into the `.sandbox`, The structure we expect:
```
.IntelliJIDEAx0/
└── plugins
    └── plugin-base
        └── lib
             │   batik-all-1.17.jar
             │   plugin-base-1.0-SNAPSHOT-instrumented.jar
             │   xml-apis-ext-1.3.04.jar
             │   xmlgraphics-commons-2.9.jar
    └── plugin-ext
        └── lib
            │   plugin-ext-1.0-SNAPSHOT-instrumented.jar
```

**Comment by Vanco** [comment]
@YannCebron please see my post above.

the 2.0.0-beta3, the `.sandbox` looks like this
![issue-plugin-structrue](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/11991700/65b742d8-57da-4acc-b85d-45eda512132f)
int this way, the `plugin-base` will have classloader issue.

**Comment by Vanco** [comment]
@YannCebron and update?

**Comment by Vanco** [comment]
I think `localPlugin(project(":plugin-base"))` should behave the same way as `plugin("plugin-base:1.0")` in the sandbox.

Assuming that the `plugin-base` has been published to the repository, the `plugin-base.zip` will be downloaded and extracted to the sandbox directory when dependency with `plugin("plugin-base:1.0")`:
```
.IntelliJIDEAx0/
└── plugins
    └── plugin-base
        └── lib
             │   batik-all-1.17.jar
             │   plugin-base-1.0-SNAPSHOT-instrumented.jar
             │   xml-apis-ext-1.3.04.jar
             │   xmlgraphics-commons-2.9.jar
```
Similarly, dependency `localPlugin(project(":plugin-base"))` should be the same result.  

However, the results of `2.0.0-beta3`,`2.0.0-beta4`,`2.0.0-beta5` now unzip the `jars` in the `lib` directory of `plugin-base.zip` into the `plugins` directory: **Wrong**
```
.IntelliJIDEAx0/
└── plugins
             │   batik-all-1.17.jar
             │   plugin-base-1.0-SNAPSHOT-instrumented.jar
             │   xml-apis-ext-1.3.04.jar
             │   xmlgraphics-commons-2.9.jar
```

**Comment by hsz** [comment]
Thanks for highlighting that. In the latest `beta9`, I've adjusted loading the local plugin — it is now consuming the output ZIP archive — in the same way it works for external plugins from JetBrains Marketplace.
