### ISSUE TITLE
Can't import/build the plugin with Android Studio 2024.2

### ISSUE THREAD

**Issue by Undin** [JetBrains/intellij-platform-gradle-plugin#1826]
### What happened?

When you try to use Android Studio 2024.2 as an IDE dependency, you get an error about missing `com.jetbrains.performancePlugin` plugin.
And indeed, Android Studio declares that it has `com.jetbrains.performancePlugin` plugin via its `product-info.json` and it doesn't contain it in `plugins` dir.
As a result, I can't use AS 2024.2 builds to build my plugin with it and be sure that it works properly with the latest version of AS.
I also tried several older versions - result is the same.

WDYT of making rules not so strict and skip plugins which are declared but don't exist on filesystem to handle such cases? Of course, it's mostly workaround, and proper fix should be done by the Android Studio team, but right now I can't do anything with it.

### Relevant log output or stack trace

```shell
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find /Users/Arseniy.Pendryak/.gradle/caches/transforms-4/d92b62efc1f741800b83e0065c850538/transformed/android-studio-2024.2.1.11-mac_arm/plugins/performanceTesting/lib/performanceTesting.jar-242.23339.11.2421.12550806+320.jar (bundledModule:com.jetbrains.performancePlugin:242.23339.11.2421.12550806+320).
Searched in the following locations:
    file:/Users/Arseniy.Pendryak/.gradle/caches/transforms-4/d92b62efc1f741800b83e0065c850538/transformed/android-studio-2024.2.1.11-mac_arm/plugins/performanceTesting/lib/performanceTesting.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactFileResolveResult.notFound(DefaultBuildableArtifactFileResolveResult.java:28)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:468)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:463)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.LocalModuleComponentRepository$LocalAccess.resolveArtifact(LocalModuleComponentRepository.java:91)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$12(ErrorHandlingModuleComponentRepository.java:172)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:227)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:194)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:170)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.FilteredModuleComponentRepository$FilteringAccess.resolveArtifact(FilteredModuleComponentRepository.java:117)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifactLater(RepositoryChainArtifactResolver.java:74)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.lambda$resolveArtifact$0(RepositoryChainArtifactResolver.java:64)
	at org.gradle.internal.model.CalculatedValueContainerFactory$SupplierBackedCalculator.calculateValue(CalculatedValueContainerFactory.java:65)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:229)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:224)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:197)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:188)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactBackedResolvedVariant$DownloadArtifactFile.run(ArtifactBackedResolvedVariant.java:189)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:238)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
	at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:236)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

https://github.com/Undin/intellij-platform-gradle-plugins-bugs/tree/android-studio-242

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

macOS

**Comment by novotnyr** [comment]
IntelliJ Plugin Verifier intentionally ignores layout entries in the `product-info.json` that do not correspond to actual filesl in the filesystem. This is addressed by [Plugin Verifier PR #1164](https://github.com/JetBrains/intellij-plugin-verifier/pull/1164).

**Comment by Undin** [comment]
But I still have this issue
Does it mean that intellij-platform grade plugin doesn't use the corresponding version if plugin verifier or something else?

@hsz

**Comment by novotnyr** [comment]
This was a side-note to a scenario that has been handled by the Plugin Verifier in parallel. As of now, IJPGP needs to adapt.

**Comment by haannnees** [comment]
Seems like it this issue is already adressed:

https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1738

**Comment by Undin** [comment]
@haannnees it's indeed a duplicate
Unfortunately, it's not addressed if we are talking about Android Studio based on 2024.2, so we still need adjustments from intellij-platform gradle plugin anyway
