### ISSUE TITLE
FileAlreadyExistsException in mono repo with multiple plugins

### ISSUE THREAD

**Issue by fp7** [JetBrains/intellij-platform-gradle-plugin#1861]
### What happened?

In mono repos and parallel gradle builds there is a concurrency issue.
The function https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/83ddc39b8ac749dccb33a2c2526a59387bfa06a2/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L1114 is not thread safe and multiple threads can try to create the same ivymodule file at the same time which leads to exceptions.

### Relevant log output or stack trace

```shell
Caused by: java.nio.file.FileAlreadyExistsException: /home/finn/dev/projects/mono/.intellijPlatform/localPlatformArtifacts/bundledModule-intellij.platform.vcs.impl-IC-243.21565.193.xml
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
        at java.base/java.nio.file.Files.createFile(Files.java:657)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.writeIvyModule(IntelliJPlatformDependenciesHelper.kt:1166)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.collectDependencies(IntelliJPlatformDependenciesHelper.kt:836)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.access$collectDependencies(IntelliJPlatformDependenciesHelper.kt:60)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$collectDependencies$2$1.invoke(IntelliJPlatformDependenciesHelper.kt:840)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$collectDependencies$2$1.invoke(IntelliJPlatformDependenciesHelper.kt:836)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.writeIvyModule(IntelliJPlatformDependenciesHelper.kt:1162)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.collectDependencies(IntelliJPlatformDependenciesHelper.kt:836)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.collectDependencies$default(IntelliJPlatformDependenciesHelper.kt:808)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$createIntelliJPlatformBundledPlugin$2.invoke(IntelliJPlatformDependenciesHelper.kt:777)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$createIntelliJPlatformBundledPlugin$2.invoke(IntelliJPlatformDependenciesHelper.kt:769)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.writeIvyModule(IntelliJPlatformDependenciesHelper.kt:1162)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.createIntelliJPlatformBundledPlugin(IntelliJPlatformDependenciesHelper.kt:769)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.access$createIntelliJPlatformBundledPlugin(IntelliJPlatformDependenciesHelper.kt:60)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$addIntelliJPlatformBundledPluginDependencies$$inlined$cachedListProvider$IntelliJPlatformGradlePlugin$1.call(IntelliJPlatformDependenciesHelper.kt:137)
        at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper$addIntelliJPlatformBundledPluginDependencies$$inlined$cachedListProvider$IntelliJPlatformGradlePlugin$1.call(IntelliJPlatformDependenc22 actionable tasks: 4 executed, 18 up-to-date
iesHelper.kt:123)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)
```

### Steps to reproduce

Run `./gradlew dependencies` in a project with multiple intellij plugins and parallel builds enabled. 
If necessary I will try to create a reproducer, but as this is a concurrency issue, it is hard to produce reliably and from the code I think it is pretty much clear that it can happen.

### Gradle IntelliJ Plugin version

2.2.1

### Gradle version

8.12

### Operating System

Linux

**Comment by hsz** [comment]
The issue is already resolved in one of the recent releases.

**Comment by fp7** [comment]
I updated to 2.5.0 some time ago and I still see the same error from above:

```
Caused by: java.nio.file.FileAlreadyExistsException: /home/finn/dev/projects/mono/.intellijPlatform/localPlatformArtifacts/IC-251.23774.435/bundledPlugin-com.intellij.java-IC-251.23774.435.xml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.createFile(Files.java:657)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.writeIvyModule(IntelliJPlatformDependenciesHelper.kt:1225)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.createIntelliJPlatformBundledPlugin(IntelliJPlatformDependenciesHelper.kt:790)
```

**Comment by hsz** [comment]
Can you please share a reproducible project so I can check that locally?

**Comment by fp7** [comment]
I put my repro project into a test. see #1940

**Comment by hsz** [comment]
It's been a while 🫣 Thanks for the detailed report — and thanks especially for authoring both the fix and the regression test! 🙏

This is resolved. The root cause was exactly what you pinpointed: in parallel/mono-repo builds, several threads could try to create the *same* local Ivy module XML under `.intellijPlatform/localPlatformArtifacts/…` at once. `writeIvyModule` used `createFile()`, which throws `FileAlreadyExistsException` when the file already exists.

The writer is now thread-safe:

- writes are serialized under a process-wide `ReentrantLock` (`IVY_MODULE_WRITE_LOCK`),
- the file is written via `writeText(...)` (overwrite) instead of `createFile()`, so an existing file no longer throws,
- and a `writtenIvyModules` dedup cache avoids re-writing the same coordinate.

Shipped in **2.10.0** (commit `6d9936ce`, #1940) and still in current `main`. It's guarded by the `--parallel` regression test `MultiPluginIntegrationTest."Parallel dependency resolution should work"`, based on your reproducer.
